import React from "react";
import {Header, MobileNav, Sidebar, Icon, Empty, PlanCard, DnsValue, ProductReadiness, ProgressCard, DetailRow, Explanation, LEVELS, severityClass, statusClass, customerPlanState, resultHeadline} from "../components/ui.jsx";

export default function TargetsPage(props) {
  const {page, setPage, productStatus, users, userId, setUserId, scans, setScans, targets, setTargets, target, setTarget, newDomain, setNewDomain, targetMessage, error, setup, setSetup, devAuthority, activationBusy, activationProduct, activateDevelopmentAccess, addTarget, verifyTarget, copyText, submitCustomerSetup, selected, setSelected, finding, setFinding, job, setJob, openScan, openFinding, closeFinding, moveFinding, findingIndex, findings, counts, active, run, stop, readiness} = props;
    const customerTargets=targets.filter(t=>!userId || String(t.user_id)===String(userId));
    const pendingTargets=customerTargets.filter(t=>t.status!=="verified");
    const verifiedTargets=customerTargets.filter(t=>t.status==="verified");
    return <div className="min-h-screen bg-slate-50"><Header productStatus={productStatus}/><MobileNav page={page} setPage={setPage}/><div className="flex min-h-[calc(100vh-70px)]"><Sidebar page={page} setPage={setPage}/><main className="min-w-0 flex-1 px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><div className="mx-auto max-w-[1080px]">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">TARGET AUTHORIZATION</p><h1 className="mt-2 text-[36px] font-black leading-none tracking-[-.045em] text-slate-950 sm:text-[46px]">Verify ownership.</h1><p className="mt-3 max-w-2xl text-[15px] leading-6 text-slate-500 sm:text-base">Before SkullHarbor scans a website, we verify that you control it. This protects your organization and helps prevent unauthorized use.</p></div><div className="flex shrink-0 gap-2"><span className="target-stat"><b>{verifiedTargets.length}</b><small>Ready</small></span><span className="target-stat"><b>{pendingTargets.length}</b><small>Waiting</small></span></div></div>
  
      <section className="mt-8 overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-soft">
        <div className="grid lg:grid-cols-[.82fr_1.18fr]">
          <div className="border-b border-slate-200 bg-slate-950 p-6 text-white sm:p-8 lg:border-b-0 lg:border-r">
            <div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><Icon name="shield"/></div>
            <h2 className="mt-5 text-2xl font-extrabold tracking-tight">Add a website you control</h2>
            <p className="mt-2 text-sm leading-6 text-slate-300">You only do this once per domain. SkullHarbor checks a unique DNS record and never treats the UI itself as authorization.</p>
            <div className="mt-6 space-y-4 text-sm"><div className="flex gap-3"><span className="step-dot">1</span><span><b className="block text-white">Enter your domain</b><small className="text-slate-400">Use the root domain, for example company.com.</small></span></div><div className="flex gap-3"><span className="step-dot">2</span><span><b className="block text-white">Add one DNS record</b><small className="text-slate-400">Copy the values SkullHarbor gives you.</small></span></div><div className="flex gap-3"><span className="step-dot">3</span><span><b className="block text-white">Verify and scan</b><small className="text-slate-400">Once verified, the website becomes available for Quick Check.</small></span></div></div>
          </div>
          <div className="p-6 sm:p-8"><div className="text-sm font-extrabold text-slate-950">Website domain</div><p className="mt-1 text-sm text-slate-500">No protocol or path is needed.</p><form onSubmit={addTarget} className="mt-5"><div className="relative"><Icon name="globe" className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input required value={newDomain} onChange={e=>setNewDomain(e.target.value)} placeholder="company.com" className="h-[58px] w-full rounded-2xl border border-slate-300 bg-white pl-12 pr-4 text-[15px] font-medium outline-none transition focus:border-slate-500 focus:ring-4 focus:ring-slate-100"/></div><button className="mt-3 inline-flex h-[52px] w-full items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-6 font-bold text-white shadow-sm transition hover:bg-emerald-700 sm:w-auto">Continue to verification <Icon name="arrow-right" className="h-4 w-4"/></button></form><div className="mt-5 flex gap-2 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500"><Icon name="info" className="mt-0.5 h-4 w-4 shrink-0"/><span>Only verify systems you own. Customer systems can instead be authorized through a trusted SkullHarbor engagement.</span></div></div>
        </div>
      </section>
  
      {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{targetMessage&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{targetMessage}</div>}
  
      <section className="mt-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold tracking-tight text-slate-950">Your websites</h2><p className="mt-1 text-sm text-slate-500">Verified websites are ready for Quick Check.</p></div></div>
      {customerTargets.length===0?<div className="mt-4 rounded-[22px] border border-dashed border-slate-300 bg-white/60"><Empty title="No websites yet" text="Add your first authorized website above."/></div>:<div className="mt-4 space-y-3">{customerTargets.map(t=><article key={t.id} className="overflow-hidden rounded-[20px] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex min-w-0 items-center gap-4"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${t.status==="verified"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}><Icon name={t.status==="verified"?"check":"globe"}/></span><div className="min-w-0"><div className="truncate font-extrabold text-slate-950">{t.domain}</div><div className="mt-1 text-xs text-slate-400">{t.status==="verified"?"Ownership verified · Ready for Quick Check":"Verification required"}</div></div></div><span className={`pill ${t.status==="verified"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{t.status==="verified"?"Verified":"Waiting for DNS"}</span></div>
        {t.status!=="verified"&&<div className="border-t border-slate-100 bg-slate-50/70 p-5 sm:p-6"><div className="mb-4"><div className="text-sm font-extrabold text-slate-900">Add this TXT record to your DNS</div><p className="mt-1 text-xs leading-5 text-slate-500">DNS updates can take a little while. Keep this page open or come back later and verify again.</p></div><div className="grid gap-3 lg:grid-cols-2"><DnsValue label="Host / Name" value={t.verification_name} copy={()=>copyText(t.verification_name)}/><DnsValue label="TXT value" value={t.verification_value} copy={()=>copyText(t.verification_value)}/></div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-slate-400">Already added the record?</span><button type="button" onClick={()=>verifyTarget(t.id)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-bold text-white hover:bg-slate-800"><Icon name="check" className="h-4 w-4"/>Verify ownership</button></div></div>}
        {t.status==="verified"&&<div className="flex items-center justify-between gap-3 border-t border-slate-100 px-5 py-4 sm:px-6"><span className="text-xs text-slate-400">Ownership is verified. Product access is checked before scanning.</span><button type="button" onClick={()=>{setTarget(`https://${t.domain}`);setPage("dashboard")}} className="inline-flex items-center gap-2 text-sm font-bold text-blue-600">Continue <Icon name="arrow-right" className="h-4 w-4"/></button></div>}
      </article>)}</div>}</section>
    </div></main></div></div>;
}
